/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormCadastro;

import MenuPrincipal.*;
import cadastroclientes.Cliente;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro11, vinality
 */
public class FormCadastro extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public FormCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNome = new javax.swing.JTextField();
        tfIdade = new javax.swing.JTextField();
        tfTelefone = new javax.swing.JFormattedTextField();
        tfCPF = new javax.swing.JFormattedTextField();
        jButton1Limpar = new javax.swing.JButton();
        jButton3Retornar = new javax.swing.JButton();
        jButton2Cadastrar = new javax.swing.JButton();
        jLabel6Telefone = new javax.swing.JLabel();
        jLabel5Idade = new javax.swing.JLabel();
        jLabel3Nome = new javax.swing.JLabel();
        jLabel2Imagem = new javax.swing.JLabel();
        jLabel1Titulo = new javax.swing.JLabel();
        jLabel7CPF = new javax.swing.JLabel();
        PlanoDeFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tfNome.setToolTipText("");
        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });
        getContentPane().add(tfNome);
        tfNome.setBounds(160, 110, 300, 26);

        tfIdade.setToolTipText("");
        tfIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdadeActionPerformed(evt);
            }
        });
        getContentPane().add(tfIdade);
        tfIdade.setBounds(160, 223, 40, 26);

        try {
            tfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(tfTelefone);
        tfTelefone.setBounds(160, 283, 140, 26);

        try {
            tfCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCPFActionPerformed(evt);
            }
        });
        getContentPane().add(tfCPF);
        tfCPF.setBounds(160, 163, 140, 26);

        jButton1Limpar.setText("Limpar");
        jButton1Limpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1LimparMouseClicked(evt);
            }
        });
        jButton1Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1LimparActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Limpar);
        jButton1Limpar.setBounds(190, 370, 80, 29);

        jButton3Retornar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconfinder_ic_keyboard_return_48px_352473.png"))); // NOI18N
        jButton3Retornar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3RetornarMouseClicked(evt);
            }
        });
        jButton3Retornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3RetornarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3Retornar);
        jButton3Retornar.setBounds(30, 40, 60, 30);

        jButton2Cadastrar.setText("Cadastrar");
        jButton2Cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2CadastrarMouseClicked(evt);
            }
        });
        jButton2Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2CadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2Cadastrar);
        jButton2Cadastrar.setBounds(50, 370, 100, 29);

        jLabel6Telefone.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 18)); // NOI18N
        jLabel6Telefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconfinder_phone_3325016 (1).png"))); // NOI18N
        jLabel6Telefone.setText("Telefone:");
        getContentPane().add(jLabel6Telefone);
        jLabel6Telefone.setBounds(30, 280, 120, 32);

        jLabel5Idade.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 18)); // NOI18N
        jLabel5Idade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconfinder_birthday-cake_1608875.png"))); // NOI18N
        jLabel5Idade.setText("Idade:");
        getContentPane().add(jLabel5Idade);
        jLabel5Idade.setBounds(30, 220, 100, 30);

        jLabel3Nome.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 18)); // NOI18N
        jLabel3Nome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconfinder_user_309035.png"))); // NOI18N
        jLabel3Nome.setText("Nome:");
        getContentPane().add(jLabel3Nome);
        jLabel3Nome.setBounds(30, 110, 110, 22);

        jLabel2Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/rsz_1rsz_kisspng-dog-grooming-puppy-cat-pet-white-dog-5a70ac435552b05161753115173335713495.png"))); // NOI18N
        jLabel2Imagem.setToolTipText("");
        getContentPane().add(jLabel2Imagem);
        jLabel2Imagem.setBounds(470, 220, 280, 250);

        jLabel1Titulo.setBackground(new java.awt.Color(1, 1, 1));
        jLabel1Titulo.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 36)); // NOI18N
        jLabel1Titulo.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1Titulo.setText("Cadastrar Cliente");
        getContentPane().add(jLabel1Titulo);
        jLabel1Titulo.setBounds(110, 25, 410, 60);

        jLabel7CPF.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 18)); // NOI18N
        jLabel7CPF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconfinder_carnet-male_416923.png"))); // NOI18N
        jLabel7CPF.setText("CPF:");
        getContentPane().add(jLabel7CPF);
        jLabel7CPF.setBounds(30, 160, 100, 30);

        PlanoDeFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/WhatsApp Image 2018-12-06 at 15.50.28.jpeg"))); // NOI18N
        getContentPane().add(PlanoDeFundo);
        PlanoDeFundo.setBounds(0, -60, 1240, 690);

        setSize(new java.awt.Dimension(639, 492));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void tfIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdadeActionPerformed

    private void tfTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTelefoneActionPerformed

    private void tfCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCPFActionPerformed

    private void jButton2CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2CadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2CadastrarActionPerformed

    private void jButton1LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1LimparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1LimparActionPerformed

    private void jButton3RetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3RetornarActionPerformed
        
    }//GEN-LAST:event_jButton3RetornarActionPerformed

    private void jButton2CadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2CadastrarMouseClicked
        // TODO add your handling code here:
        Cliente c = new Cliente();
        c.setNome(tfNome.getText());
        c.setTelefone(tfTelefone.getText());
        int idade = Integer.parseInt(tfIdade.getText());
        c.setIdade(idade);
        c.setCpf(tfCPF.getText());
        JOptionPane.showMessageDialog(this, "Cliente cadastrado\n Nome: " + c.getNome() + "\n" + "CPF: " + c.getCpf() + "\n" + "Idade: " + c.getIdade() + "\n" + "Telefone: " + c.getTelefone());
        clearFields();
    }//GEN-LAST:event_jButton2CadastrarMouseClicked

    private void jButton3RetornarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3RetornarMouseClicked
        // TODO add your handling code here:
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3RetornarMouseClicked

    private void jButton1LimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1LimparMouseClicked
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_jButton1LimparMouseClicked
    
    private void clearFields(){
        tfNome.setText("");
        tfTelefone.setText("");
        tfIdade.setText("");
        tfCPF.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PlanoDeFundo;
    private javax.swing.JButton jButton1Limpar;
    private javax.swing.JButton jButton2Cadastrar;
    private javax.swing.JButton jButton3Retornar;
    private javax.swing.JLabel jLabel1Titulo;
    private javax.swing.JLabel jLabel2Imagem;
    private javax.swing.JLabel jLabel3Nome;
    private javax.swing.JLabel jLabel5Idade;
    private javax.swing.JLabel jLabel6Telefone;
    private javax.swing.JLabel jLabel7CPF;
    private javax.swing.JFormattedTextField tfCPF;
    private javax.swing.JTextField tfIdade;
    private javax.swing.JTextField tfNome;
    private javax.swing.JFormattedTextField tfTelefone;
    // End of variables declaration//GEN-END:variables
}
