/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormCadastro;

import MenuPrincipal.*;
import cadastroclientes.Cliente;
import cadastroclientes.Conexao;
import cadastroclientes.OperacoesBD;
import cadastroclientes.Paciente;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro11, vinality
 */

public class FormInserirPet extends javax.swing.JFrame {
    private Connection conn;

    public String getCpf_cliente() {
        return cpf_cliente;
    }

    public void setCpf_cliente(String cpf_cliente) {
        this.cpf_cliente = cpf_cliente;
    }
    private String cpf_cliente;
    
    /**
     * Creates new form Menu
     */
    public FormInserirPet(String cpf) {
        initComponents();
        conn = Conexao.getConnection();
        this.cpf_cliente = cpf;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNomePet = new javax.swing.JTextField();
        jLabel6NomePet = new javax.swing.JLabel();
        jLabel7RGA = new javax.swing.JLabel();
        tfRGA = new javax.swing.JFormattedTextField();
        jButton1Limpar = new javax.swing.JButton();
        jButton3Retornar = new javax.swing.JButton();
        jButton2Cadastrar = new javax.swing.JButton();
        jLabel2Imagem = new javax.swing.JLabel();
        jLabel1Titulo = new javax.swing.JLabel();
        PlanoDeFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tfNomePet.setToolTipText("");
        tfNomePet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomePetActionPerformed(evt);
            }
        });
        getContentPane().add(tfNomePet);
        tfNomePet.setBounds(210, 133, 230, 20);

        jLabel6NomePet.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 18)); // NOI18N
        jLabel6NomePet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconfinder_paw_1608784 (1).png"))); // NOI18N
        jLabel6NomePet.setText("Nome do Pet:");
        getContentPane().add(jLabel6NomePet);
        jLabel6NomePet.setBounds(40, 130, 170, 32);

        jLabel7RGA.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 18)); // NOI18N
        jLabel7RGA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconfinder_carnet-male_416923.png"))); // NOI18N
        jLabel7RGA.setText("RGA:");
        getContentPane().add(jLabel7RGA);
        jLabel7RGA.setBounds(40, 190, 100, 30);

        try {
            tfRGA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfRGA.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        tfRGA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRGAActionPerformed(evt);
            }
        });
        getContentPane().add(tfRGA);
        tfRGA.setBounds(170, 193, 80, 20);

        jButton1Limpar.setText("Limpar");
        jButton1Limpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1LimparMouseClicked(evt);
            }
        });
        jButton1Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1LimparActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Limpar);
        jButton1Limpar.setBounds(170, 340, 80, 23);

        jButton3Retornar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconfinder_ic_keyboard_return_48px_352473.png"))); // NOI18N
        jButton3Retornar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3RetornarMouseClicked(evt);
            }
        });
        jButton3Retornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3RetornarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3Retornar);
        jButton3Retornar.setBounds(30, 40, 60, 30);

        jButton2Cadastrar.setText("Cadastrar");
        jButton2Cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2CadastrarMouseClicked(evt);
            }
        });
        jButton2Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2CadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2Cadastrar);
        jButton2Cadastrar.setBounds(30, 340, 100, 23);

        jLabel2Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/rsz_1rsz_kisspng-dog-grooming-puppy-cat-pet-white-dog-5a70ac435552b05161753115173335713495.png"))); // NOI18N
        jLabel2Imagem.setToolTipText("");
        getContentPane().add(jLabel2Imagem);
        jLabel2Imagem.setBounds(470, 220, 280, 250);

        jLabel1Titulo.setBackground(new java.awt.Color(1, 1, 1));
        jLabel1Titulo.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 36)); // NOI18N
        jLabel1Titulo.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1Titulo.setText("Cadastrar Cliente");
        getContentPane().add(jLabel1Titulo);
        jLabel1Titulo.setBounds(110, 25, 410, 60);

        PlanoDeFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/WhatsApp Image 2018-12-06 at 15.50.28.jpeg"))); // NOI18N
        getContentPane().add(PlanoDeFundo);
        PlanoDeFundo.setBounds(0, -60, 1240, 690);

        setSize(new java.awt.Dimension(639, 492));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomePetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomePetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomePetActionPerformed

    private void jButton2CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2CadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2CadastrarActionPerformed

    private void jButton1LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1LimparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1LimparActionPerformed

    private void jButton3RetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3RetornarActionPerformed
        
    }//GEN-LAST:event_jButton3RetornarActionPerformed

    private void jButton2CadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2CadastrarMouseClicked
        // TODO add your handling code here:
        Paciente p = new Paciente();
        int flag = 0;
        
        p.setNome(tfNomePet.getText());
        p.setRGA(tfRGA.getText()); 

        if (p.getRGA().equals("") || p.getNome().equals("")) {
            JOptionPane.showMessageDialog(null, "Favor preencher todos os campos.");
            return;
         }
        
        OperacoesBD op=new OperacoesBD();
        try {
            op.salvarPet((Connection) conn, this.getCpf_cliente() , p);
            JOptionPane.showMessageDialog(this,"Paciente Cadastrado:"+(String)tfRGA.getText());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Paciente Não Cadastrado");
            Logger.getLogger(FormCadastro.class.getName()).log(Level.SEVERE, null, ex);
            flag = 1;
        }
        
        int resposta;
        Object[] options = {"Sim", "Não"};
        resposta = JOptionPane.showOptionDialog( null,"Deseja inserir mais um pet?", "Inserir", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        
        if(flag == 0 && resposta == 0){
            new FormInserirPet(this.getCpf_cliente()).setVisible(true);
            this.dispose();
        }
        else{
            new Menu().setVisible(true);
            this.dispose();
        }
        
        clearFields();
    }//GEN-LAST:event_jButton2CadastrarMouseClicked

    private void jButton3RetornarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3RetornarMouseClicked
        // TODO add your handling code here:
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3RetornarMouseClicked

    private void jButton1LimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1LimparMouseClicked
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_jButton1LimparMouseClicked

    private void tfRGAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRGAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRGAActionPerformed
    
    private void clearFields(){
        tfNomePet.setText("");
        tfRGA.setText("");
    }
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PlanoDeFundo;
    private javax.swing.JButton jButton1Limpar;
    private javax.swing.JButton jButton2Cadastrar;
    private javax.swing.JButton jButton3Retornar;
    private javax.swing.JLabel jLabel1Titulo;
    private javax.swing.JLabel jLabel2Imagem;
    private javax.swing.JLabel jLabel6NomePet;
    private javax.swing.JLabel jLabel7RGA;
    private javax.swing.JTextField tfNomePet;
    private javax.swing.JFormattedTextField tfRGA;
    // End of variables declaration//GEN-END:variables
}
