/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MenuPrincipal;

import FormCadastro.FormCadastro;
import alterarcadastro.FormAlterar1;
import buscaclientes.FormBusca;

/**
 *
 * @author pedro11, vinality
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1CadastrarCliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3ListarClientes1 = new javax.swing.JButton();
        jButton3ListarClientes = new javax.swing.JButton();
        jButton3RemoverCliente = new javax.swing.JButton();
        jButton2BuscarCliente = new javax.swing.JButton();
        PlanoDeFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/rsz_kisspng-siberian-husky-puppy-pet-meng-meng-da-husky-5a7a4cbc0d8aa22671031415179644760555.png"))); // NOI18N
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(410, 240, 250, 220);

        jButton1CadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/rsz_iconfinder_add_user_309049.png"))); // NOI18N
        jButton1CadastrarCliente.setText("Cadastrar Cliente");
        jButton1CadastrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1CadastrarClienteMouseClicked(evt);
            }
        });
        jButton1CadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1CadastrarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1CadastrarCliente);
        jButton1CadastrarCliente.setBounds(60, 120, 200, 50);

        jLabel1.setBackground(new java.awt.Color(1, 1, 1));
        jLabel1.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Módulo Clientes");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 30, 370, 50);

        jButton3ListarClientes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconfinder_icon-folder_211608.png"))); // NOI18N
        jButton3ListarClientes1.setText("Alterar Cliente");
        jButton3ListarClientes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3ListarClientes1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3ListarClientes1);
        jButton3ListarClientes1.setBounds(60, 330, 200, 50);

        jButton3ListarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconfinder_icon-folder_211608.png"))); // NOI18N
        jButton3ListarClientes.setText("Listar Clientes");
        getContentPane().add(jButton3ListarClientes);
        jButton3ListarClientes.setBounds(60, 400, 200, 50);

        jButton3RemoverCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/rsz_iconfinder_remove_user_309037.png"))); // NOI18N
        jButton3RemoverCliente.setText("Remover Cliente");
        getContentPane().add(jButton3RemoverCliente);
        jButton3RemoverCliente.setBounds(60, 190, 200, 50);

        jButton2BuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/rsz_iconfinder_search-80px_510919.png"))); // NOI18N
        jButton2BuscarCliente.setText("Buscar Cliente");
        jButton2BuscarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2BuscarClienteMouseClicked(evt);
            }
        });
        jButton2BuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2BuscarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2BuscarCliente);
        jButton2BuscarCliente.setBounds(60, 260, 200, 50);

        PlanoDeFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/WhatsApp Image 2018-12-06 at 15.50.28.jpeg"))); // NOI18N
        getContentPane().add(PlanoDeFundo);
        PlanoDeFundo.setBounds(0, -60, 1240, 690);

        setSize(new java.awt.Dimension(649, 502));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2BuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2BuscarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2BuscarClienteActionPerformed

    private void jButton1CadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1CadastrarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1CadastrarClienteActionPerformed

    private void jButton1CadastrarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1CadastrarClienteMouseClicked
        // TODO add your handling code here:
        new FormCadastro().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1CadastrarClienteMouseClicked

    private void jButton2BuscarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2BuscarClienteMouseClicked
        // TODO add your handling code here:
        new FormBusca().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2BuscarClienteMouseClicked

    private void jButton3ListarClientes1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3ListarClientes1MouseClicked
        new FormAlterar1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ListarClientes1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PlanoDeFundo;
    private javax.swing.JButton jButton1CadastrarCliente;
    private javax.swing.JButton jButton2BuscarCliente;
    private javax.swing.JButton jButton3ListarClientes;
    private javax.swing.JButton jButton3ListarClientes1;
    private javax.swing.JButton jButton3RemoverCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
